[package]
name = "cargo-glados"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/blyxyas/cargo-glados"
description = "GlaDOS in your terminal?"
license-file= "LICENSE"

[dependencies]
soloud = "1.0.5"
tiny-rng = "0.3.0"
